version: "3"
services:
    nginx:
        ports:
            - "3000:80"
    node_app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=rafiadw
            - MONGO_PASSWORD=12345
            - REDIS_SECRET=secret
        command: npm run dev
