version: "3"
services:
    nginx:
        ports:
            - "80:80"
    node_app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - REDIS_SECRET=${REDIS_SECRET}
        command: node index.js
