version: "3"
services:
    node_app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            # env_file:
            #     - ./.env
        volumes:
            - .:/app
            - /app/node_modules
