version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node_app:
        deploy:
            replicas: 8
            restart_policy:
                condition: any
            update_config:
                parallelism: 2
                delay: 15s

        build: .
        environment:
            - PORT=3000
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongo-db:/data/db

    redis:
        image: redis

volumes:
    mongo-db:
